In [1]:
import torch

In [6]:
# scalar value
x=torch.empty(1)
print(x)

tensor([1.4013e-45])


In [7]:
# print a 1D vector
x=torch.empty(3)
print(x)

tensor([-2.2431e+24,  7.8333e-43,  5.7397e-42])


In [8]:
# create a matix
x=torch.empty(2,3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 1.8754e+28],
        [6.3455e-10, 3.3614e+21, 1.0084e-11]])


In [9]:
# create a 3d
x=torch.empty(2,3,5)
print(x)

tensor([[[9.2755e-39, 1.0561e-38, 5.9694e-39, 6.3367e-39, 8.4490e-39],
         [1.0286e-38, 6.2450e-39, 1.0653e-38, 8.4490e-39, 1.0194e-38],
         [8.9082e-39, 8.4490e-39, 1.0469e-38, 9.4592e-39, 8.9082e-39]],

        [[1.0561e-38, 7.3470e-39, 1.0653e-38, 1.0194e-38, 8.4490e-39],
         [1.1112e-38, 9.5511e-39, 1.0102e-38, 5.1429e-39, 6.9796e-39],
         [9.0000e-39, 1.0561e-38, 1.0653e-38, 4.1327e-39, 8.9082e-39]]])


In [10]:
# create a 4d
x=torch.empty(2,3,5,7)
print(x)

tensor([[[[-9.2898e+37,  7.8333e-43, -9.2899e+37,  7.8333e-43, -9.2900e+37,
            7.8333e-43, -9.2901e+37],
          [ 7.8333e-43, -9.2902e+37,  7.8333e-43, -9.2902e+37,  7.8333e-43,
           -9.2903e+37,  7.8333e-43],
          [-9.2904e+37,  7.8333e-43, -9.2905e+37,  7.8333e-43, -9.2906e+37,
            7.8333e-43, -9.2906e+37],
          [ 7.8333e-43, -9.2907e+37,  7.8333e-43, -9.2908e+37,  7.8333e-43,
           -9.2909e+37,  7.8333e-43],
          [-9.2910e+37,  7.8333e-43, -9.2910e+37,  7.8333e-43, -9.2911e+37,
            7.8333e-43, -9.2912e+37]],

         [[ 7.8333e-43, -9.2913e+37,  7.8333e-43, -9.2914e+37,  7.8333e-43,
           -9.2915e+37,  7.8333e-43],
          [-9.2915e+37,  7.8333e-43, -9.2916e+37,  7.8333e-43, -9.2917e+37,
            7.8333e-43, -9.2918e+37],
          [ 7.8333e-43, -9.2919e+37,  7.8333e-43, -9.2919e+37,  7.8333e-43,
           -9.2920e+37,  7.8333e-43],
          [-9.3171e+37,  7.8333e-43, -9.3172e+37,  7.8333e-43, -9.3173e+37,
          

In [11]:
# get random values
# create a 2d
x=torch.rand(2,5)
print(x)

tensor([[0.7357, 0.7651, 0.5839, 0.3400, 0.3871],
        [0.5449, 0.9604, 0.5626, 0.2951, 0.6827]])


In [12]:
# make a matrix with zeros in it
x=torch.zeros(4,5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [13]:
# get ones in all the items
x=torch.ones(2,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
# check the datatype
x.dtype

torch.float32

In [17]:
# we can also the datatype while declaring
x=torch.empty(2,3,dtype=torch.int)
x
# we can have int,double or float with size 15,32

tensor([[ 942891876,  876110180,  892876594],
        [1633957433, 1701078069,  842216033]], dtype=torch.int32)

In [18]:
# print the size
x.size()

torch.Size([2, 3])

In [19]:
# we can also contruct a tensor from data, like from a list
x=torch.tensor([4,5,3,2])
x

tensor([4, 5, 3, 2])

let's talk about some basic operations we can do 

In [20]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)
print(y)
# z=x+y element wise addition
z=torch.add(x,y)
print(z)

tensor([[0.8790, 0.6180],
        [0.2469, 0.3499]])
tensor([[0.3938, 0.6797],
        [0.1928, 0.1834]])
tensor([[1.2728, 1.2977],
        [0.4397, 0.5333]])


In [23]:
# we can also do an inplace addition, for example
print("y earlier: ",y)
y.add_(x)
# this will modify the value of y
print("y now: ")
print(y)
# every function that has an underscore will do an inplace operation

y earlier:  tensor([[2.1519, 1.9157],
        [0.6866, 0.8832]])
y now: 
tensor([[3.0309, 2.5336],
        [0.9334, 1.2330]])


In [25]:
z=x*y
p=x/y
q=x-y
print(z,"\n",p,"\n",q)

tensor([[2.6642, 1.5657],
        [0.2304, 0.4314]]) 
 tensor([[0.2900, 0.2439],
        [0.2645, 0.2837]]) 
 tensor([[-2.1519, -1.9157],
        [-0.6866, -0.8832]])


In [28]:
# we can also do python operation
x=torch.rand(5,3)
print(x)
print(x[1,:]) # row 1 and all columns
print(x[1:3,:]) # row 1,2 and all columns

tensor([[0.2932, 0.0444, 0.7846],
        [0.4551, 0.7858, 0.5063],
        [0.1282, 0.9515, 0.7713],
        [0.2329, 0.3025, 0.3622],
        [0.0241, 0.8713, 0.3532]])
tensor([0.4551, 0.7858, 0.5063])
tensor([[0.4551, 0.7858, 0.5063],
        [0.1282, 0.9515, 0.7713]])


In [29]:
print(x[1,1].item())

0.7857858538627625


In [33]:
# reshaping our tensor
x=torch.rand(4,4)
print(x)
y=x.view(16) # we can a 1d array, no of elements is same
print(y)
# so we know only the no of columns, then we can put -1 in place of number of row
y=x.view(-1,8)# this will create a 2 dimensional array
print(y)

tensor([[0.5740, 0.3756, 0.9214, 0.7246],
        [0.3339, 0.3778, 0.9971, 0.2892],
        [0.1905, 0.4621, 0.4627, 0.1956],
        [0.2744, 0.5803, 0.6144, 0.3598]])
tensor([0.5740, 0.3756, 0.9214, 0.7246, 0.3339, 0.3778, 0.9971, 0.2892, 0.1905,
        0.4621, 0.4627, 0.1956, 0.2744, 0.5803, 0.6144, 0.3598])
tensor([[0.5740, 0.3756, 0.9214, 0.7246, 0.3339, 0.3778, 0.9971, 0.2892],
        [0.1905, 0.4621, 0.4627, 0.1956, 0.2744, 0.5803, 0.6144, 0.3598]])


In [34]:
print(y.size())

torch.Size([2, 8])


In [37]:
# converting from numpy array to torch tensor
import numpy as np
a=torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [40]:
# now we can convert a to numpy array
b=a.numpy()
print(b)
print(type(b))


[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [42]:
a.add_(1)
# if change the value of a now, b value will change too because they are sharing the same memory location
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [43]:
# to convert numpy to torch
a=np.ones(5)
print(a)
b=torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [50]:
if torch.cuda.is_available():
    print("yes")
else:
    print("no")

no


In [51]:
x=torch.ones(5,requires_grad=True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)