In [1]:
import torch

In [17]:
x=torch.randn(3,requires_grad=True) # by default this is false
print(x)
# so whenever we do any sort of computations, pytorch will create a computational graph for us

tensor([ 1.3301, -0.2042,  0.0915], requires_grad=True)


In [18]:
y=x+2
# just like the back propagation

since, we specified that it requires a gradient, pytorch will automatically create a function for us and this 
will be used for create gradient

In [19]:
print(y)
# pytorch created a AddBackward0 function

tensor([3.3301, 1.7958, 2.0915], grad_fn=<AddBackward0>)


In [9]:
z=y*y*2
print(z)
# pytorhc created a MulBackward0 function

tensor([1.2444e-02, 1.3385e+01, 4.8658e-01], grad_fn=<MulBackward0>)


In [20]:
z=z.mean()
print(z)

tensor(4.6279, grad_fn=<MeanBackward0>)


In [22]:
z.backward()
print(x.grad)

None


In [25]:
v=torch.tensor([.1,1.0,0.001],dtype=torch.float64)


In [26]:
x=torch.randn(3,requires_grad=True)
x

tensor([ 0.2961, -0.5729,  0.9059], requires_grad=True)

In [27]:
# now we want to know to prevent it from tracking the gradient, we have three option
# first to call requires_grad function and set it to false
#x.requires_grad(False)
# second is to call x.detach, this will create a new tensor that will not require the gradient
# x.detach()
# third with torch.no_grad()
# x.no_grad()

In [29]:
x.requires_grad_(False)
print(x)
print("now, we can see that it doesn't have the requirs grad option")

tensor([ 0.2961, -0.5729,  0.9059])
now, we can see that it doesn't have the requirs grad option


In [31]:
x=torch.randn(3,requires_grad=True)
print(x)
y=x.detach()
print(y)
print("it has created a vector y which doesn't need have requires grad")

tensor([ 1.4263, -0.9636,  0.5344], requires_grad=True)
tensor([ 1.4263, -0.9636,  0.5344])
it has created a vector y which doesn't need have requires grad


In [36]:
x=torch.randn(3,requires_grad=True)
with torch.no_grad():
    y=x-1+1
    print(y)

tensor([1.0201, 2.3712, 0.1596])


In [37]:
# whenver we call the backward function, then the gradient for this tensor will be accumulated into the .grad attribute
# that is, the values will be summed up
# let's have a training example
weights=torch.ones(4,requires_grad=True)
for epoch in range(1):
    model_output=(weights*3).sum()

    model_output.backward()

    print(weights.grad)

tensor([3., 3., 3., 3.])


In [38]:
# now if we do another iteration
for epoch in range(1):
    model_output=(weights*3).sum()

    model_output.backward()

    print(weights.grad)

tensor([6., 6., 6., 6.])


In [39]:
# do third iteration
for epoch in range(1):
    model_output=(weights*3).sum()

    model_output.backward()

    print(weights.grad)

tensor([9., 9., 9., 9.])


In [41]:
weights=torch.ones(4,requires_grad=True)
for epoch in range(3):
    model_output=(weights*3).sum()

    model_output.backward()

    print(weights.grad)
print("this is obviously wrong here")

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])
this is obviously wrong here


In [42]:
weights=torch.ones(4,requires_grad=True)
for epoch in range(3):
    model_output=(weights*3).sum()

    model_output.backward()

    print(weights.grad)

    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [50]:
# later we will word on torch optimizer, let's use ones of them
weights=torch.ones(4,requires_grad=True)
optimizer=torch.optim.SGD([weights],lr=0.01)
optimizer.step()
optimizer.zero_grad()
print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.01
    momentum: 0
    nesterov: False
    weight_decay: 0
)
